<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Post;

class PostsTableSeeder extends Seeder
{
    private $post;

    public function __construct(Post $post)
    {
        $this->post = $post;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $posts = [
            [
                'id' => 1,
                'user_id' => 3,
                'title' => 'SUSHI Making Experience JOY ASAKUSA',
                'article' => "The sushi was delicious! We took a lot of pictures and were able to record many fun memories.\n\nSushi Nigiri Experience Facility, where you can enjoy sushi culture with fresh sushi items and an immersive production space full of entertainment.",
                'prefecture_id' => 13,
                'area_id' => 3,
                'visit_date' => '2024-01-11',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '東京都中央区築地2-15-19',
                'event_longitude' => 139.7704,
                'event_latitude' => 35.6652,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 2,
                'user_id' => 4,
                'title' => 'Sapporo Snow Festival',
                'article' => "A festival of snow and ice with beautiful snow sculptures and lights. (Sapporo)",
                'prefecture_id' => 1,
                'area_id' => 1,
                'visit_date' => null,
                'start_date' => '2024-09-03',
                'end_date' => '2024-09-15',
                'event_address' => '北海道札幌市東区栄町８８５−１',
                'event_longitude' => 141.374972,
                'event_latitude' => 43.117694,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 3,
                'user_id' => 3,
                'title' => 'Okayama Glamping Setorini Bizen',
                'article' => "Enjoy the nature of Okayama in a glamping resort with a private pool. (Bizen City)\n\nIntroduce foreign cuisine: - Work at an event or restaurant that introduces your country's cuisine to Japanese people.\n\nCommunicate slowly and in simple English: - Japanese people are often not good at English, but if you speak simple English, you can get through.",
                'prefecture_id' => 33,
                'area_id' => 6,
                'visit_date' => '2024-02-22',
                'start_date' => NULL,
                'end_date' => NULL,
                'event_address' => '岡山県備前市日生町日生3018',
                'event_longitude' => 134.2029,
                'event_latitude' => 34.7244,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 4,
                'user_id' => 2,
                'title' => 'Sauna',
                'article' => "Resort glamping facility with sauna and jacuzzi, where you can enjoy seasonal foods from Awaji. (THE GOAT AWAJI, Awaji City)\n\nTipping is not required: - There is no need to tip restaurant waiters or cab drivers. Service charges are included.",
                'prefecture_id' => 28,
                'area_id' => 5,
                'visit_date' => '2024-03-03',
                'start_date' => NULL,
                'end_date' => NULL,
                'event_address' => '兵庫県淡路市',
                'event_longitude' => 134.9071,
                'event_latitude' => 34.5014,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 5,
                'user_id' => 5,
                'title' => 'Awa Odori Dance',
                'article' => "Great experience!!\nIt is a festival of dance and colorful costumes and dancing.",
                'prefecture_id' => 36,
                'area_id' => 7,
                'visit_date' => '2024-10-12',
                'start_date' => '2024-10-12',
                'end_date' => '2024-10-15',
                'event_address' => '徳島県徳島市南内町１丁目４',
                'event_longitude' => 134.551529,
                'event_latitude' => 34.068751,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 6,
                'user_id' => 2,
                'title' => 'Sumo',
                'article' => "Sumo is a traditional Japanese Shinto ritual and martial art sport in which wrestlers fight on the ring. You can enjoy the powerful efforts and techniques when you watch a match! (Kokugikan)\n\nTourist Guide: - You can work as a tourist guide to show you around tourist attractions and cultural sites.\n\nLeft side of the road: - In Japan, cars and bicycles also drive on the left side of the road. It's okay once you get used to it, but if you're new to it, be careful.\n",
                'prefecture_id' => 40,
                'area_id' => 8,
                'visit_date' => '2024-09-18',
                'start_date' => '2024-09-18',
                'end_date' => '2024-09-22',
                'event_address' => '東京都墨田区横網１丁目３−２８',
                'event_longitude' => 139.793228746763,
                'event_latitude' => 35.697165153296,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 7,
                'user_id' => 5,
                'title' => 'Agricultural Experience',
                'article' => "Some trips made me feel grateful to the locals who helped me in my time of need.\n\nWWOOF Japan is a program that provides volunteer experience at a farmhouse. You can learn through farm work such as weeding, harvesting, and caring for animals.\n\n Homestay Hosts: - Allow foreigners to homestay in your home and share Japanese life and culture.",
                'prefecture_id' => 15,
                'area_id' => 4,
                'visit_date' => '2024-04-04',
                'start_date' => NULL,
                'end_date' => NULL,
                'event_address' => '東京都渋谷区代々木2-23-1',
                'event_longitude' => 139.7022,
                'event_latitude' => 35.6833,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 8,
                'user_id' => 4,
                'title' => 'Tokyo Ramen Festa ',
                'article' => "10 ramen restaurants from all over Japan will open their stores. The event will be held at Komazawa Olympic Park.\n\nEating noodles noisily: - It is Japanese etiquette to eat noodles such as ramen and soba noodles noisily.",
                'prefecture_id' => 13,
                'area_id' => 3,
                'visit_date' => '2024-09-24',
                'start_date' => '2024-09-24',
                'end_date' => '2024-10-03',
                'event_address' => '東京都世田谷区駒沢公園１',
                'event_longitude' => 139.661946495187,
                'event_latitude' => 35.6254286733299,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 9,
                'user_id' => 5,
                'title' => 'Onsen Kawaguchiko in the Sky',
                'article' => "The trip around with my family is a wonderful memory filled with fun and pleasant fatigue. We were impressed by Mt.\n\nOnsen villa for a special time with views of Mt. Fuji and Lake Kawaguchi. （Fuji, Fuji Five Lakes, and Fujiyoshida.)\n\nShoe-removal customs:- Shoes are removed when entering a house or traditional building. Be aware that you may also have to take off your shoes in restaurants.",
                'prefecture_id' => 19,
                'area_id' => 4,
                'visit_date' => '2024-05-05',
                'start_date' => NULL,
                'end_date' => NULL,
                'event_address' => '山梨県南都留郡富士河口湖町船津6677',
                'event_longitude' => 138.7602,
                'event_latitude' => 35.5059,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 10,
                'user_id' => 4,
                'title' => 'Onimatsuri',
                'article' => "It was a shocking experience.\nThe \"Onimatsuri\" is a \"strange festival under heaven\" held at Takiyama Temple. Huge torches are brought in and demons dance wildly. A fire battle ensues, and the crazy spectacle is the talk of the town.",
                'prefecture_id' => 23,
                'area_id' => 4,
                'visit_date' => '2024-09-10',
                'start_date' => '2024-09-10',
                'end_date' => '2024-09-11',
                'event_address' => '愛知県岡崎市滝町山籠１０７',
                'event_longitude' => 137.205782661388,
                'event_latitude' => 34.9897793514653,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 11,
                'user_id' => 5,
                'title' => 'AnimeJapan',
                'article' => "AnimeJapan is one of the world's largest anime events held annually at Tokyo Big Sight. It will be a fun-filled two days for anime fans! 🌟Anime production companies, voice actors, and fans gather in one place. There will be plenty of exhibition booths and stage events.\n\nEnglish Teaching: - Help Japanese students and business people improve their English skills by teaching English as a native language.",
                'prefecture_id' => 13,
                'area_id' => 3,
                'visit_date' => '2024-09-23',
                'start_date' => '2024-09-23',
                'end_date' => '2024-09-24',
                'event_address' => '東京都江東区有明３丁目１１−１',
                'event_longitude' => 139.797528170056,
                'event_latitude' => 35.6323067547106,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 12,
                'user_id' => 3,
                'title' => 'Shakyo',
                'article' => "Shakyo is one of the traditional Japanese cultural traditions of transcribing sutras.It is performed for the purposes of faith, mental stability, and the repose of the souls of the deceased. Specifically, it refers to the act of copying sutras such as the Heart Sutra with a brush. Practicing sutra copying has many benefits, such as improving concentration, perseverance, and writing. Even beginners can try it easily, so if you are interested, please give it a try!\nHomestay Host: - You can share Japanese life and culture by homestaying a foreigner in your home.\n\nShoes off custom: - Take off your shoes when entering a house or traditional building. Be careful.",
                'prefecture_id' => 43,
                'area_id' => 4,
                'visit_date' => '2024-08-10',
                'start_date' => NULL,
                'end_date' => NULL,
                'event_address' => '和歌山県伊都郡高野町高野山',
                'event_longitude' => 135.5850,
                'event_latitude' => 34.2123,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 13,
                'user_id' => 5,
                'title' => 'Kishiwada Danjiri Festival',
                'article' => "A stunning experience.\nIt is a very powerful festival with floats parading around. (Kishiwada City)\n\nTranslation and Interpretation: - We can help facilitate communication by providing translation and interpretation from English to Japanese or Japanese to English.\n",
                'prefecture_id' => 27,
                'area_id' => 5,
                'visit_date' => '2024-10-15',
                'start_date' => '2024-10-15',
                'end_date' => '2024-10-20',
                'event_address' => '大阪府岸和田市本町１１−２３',
                'event_longitude' => 135.368312252178,
                'event_latitude' => 34.460263462657,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 14,
                'user_id' => 2,
                'title' => 'Gion Festival',
                'article' => "This historic festival has been going on for over 100 years, and the Yamahoko Junko is the highlight. (Kyoto, Japan)\n\nTourist Guide: - You can work as a tourist guide to show you around tourist attractions and cultural sites.\n\nCarry cash: - Although more and more places in Japan accept credit cards and electronic money, it is convenient to carry cash.",
                'prefecture_id' => 26,
                'area_id' => 5,
                'visit_date' => '2024-09-01',
                'start_date' => '2024-09-01',
                'end_date' => '2024-09-30',
                'event_address' => '京都府京都市東山区祇園町北側６２５',
                'event_longitude' => 135.778462124667,
                'event_latitude' => 35.0040075012403,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 15,
                'user_id' => 3,
                'title' => 'Kabuki',
                'article' => "Watching kabuki is a wonderful experience! You will love Japanese culture!\n\nEnglish Teaching: - Help Japanese students and business people improve their English skills by teaching English as a native language.\n\nForeign language support is limited: - Foreign language support can be scarce outside of urban and tourist areas. Make use of translation apps.",
                'prefecture_id' => 13,
                'area_id' => 3,
                'visit_date' => '2024-06-06',
                'start_date' => NULL,
                'end_date' => NULL,
                'event_address' => '東京都中央区銀座4丁目12-15',
                'event_longitude' => 139.7680,
                'event_latitude' => 35.6697,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            [
                'id' => 16,
                'user_id' => 2,
                'title' => 'Aomori Nebuta Festival',
                'article' => "I was very impressed with the view!\nAomori Nebuta Festival is a powerful festival held in August, where huge Nebuta floats are paraded through the streets.\n\n Translation and Interpretation: - We can help facilitate communication by providing translation and interpretation from English to Japanese or Japanese to English.\n\nFew trash cans: - In Japan, there are few trash cans outside, so it is common to take your trash home with you.",
                'prefecture_id' => 2,
                'area_id' => 2,
                'visit_date' => '2024-09-02',
                'start_date' => '2024-09-02',
                'end_date' => '2024-09-07',
                'event_address' => '青森県青森市中央１丁目',
                'event_longitude' => 140.746433612561,
                'event_latitude' => 40.8232599772706,
                'language' => 'en-US',
                'created_at' => NOW(),
                'updated_at' => NOW()
            ],
            #Add
            [
                'id' => 17,
                'user_id' => 6,
                'title' => 'Sapporo Snow Festival',
                'article' => 'Winter festival with snow and ice sculptures on display',
                'prefecture_id' => 1,
                'area_id' => null,
                'visit_date' => '2024-02-01',
                'start_date' => '2024-02-01',
                'end_date' => '2024-02-01',
                'event_address' => '札幌市中央区大通公園',
                'event_longitude' => 141.346391,
                'event_latitude' => 43.05972,
                'language' => 'en-US',
                'created_at' => '2024-02-01',
                'updated_at' => NOW()
            ],
            [
                'id' => 18,
                'user_id' => 6,
                'title' => 'Nebuta Festival (Aomori)',
                'article' => 'Summer festival in which large Nebuta (lanterns) are paraded through the streets',
                'prefecture_id' => 2,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '青森県青森市新町1-2-18',
                'event_longitude' => 140.7400,
                'event_latitude' => 40.8246,
                'language' => 'en-GB',
                'created_at' => '2024-01-01',
                'updated_at' => NOW()
            ],
            [
                'id' => 19,
                'user_id' => 6,
                'title' => 'Morioka Sansa Odori Festival (Tokushima)',
                'article' => 'Festival d’été avec des tambours taiko et des danses',
                'prefecture_id' => 3,
                'area_id' => null,
                'visit_date' => '2024-05-05',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '岩手県盛岡市中央通1',
                'event_longitude' => 141.15421,
                'event_latitude' => 39.7016,
                'language' => 'fr-FR',
                'created_at' => '2024-05-05',
                'updated_at' => NOW()
            ],
            [
                'id' => 20,
                'user_id' => 6,
                'title' => 'Sendai Tanabata Festival',
                'article' => 'Bunte Tanabata-Dekorationen schmücken die Stadt3',
                'prefecture_id' => 4,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '宮城県仙台市青葉区中央1丁目2',
                'event_longitude' => 140.88182,
                'event_latitude' => 38.2618,
                'language' => 'de-DE',
                'created_at' => '2024-01-02',
                'updated_at' => NOW()
            ],
            [
                'id' => 21,
                'user_id' => 7,
                'title' => 'Sapporo Autumn Fest',
                'article' => 'This gourmet festival is held in Odori Park in Sapporo. Delicious foods from Hokkaido will be gathered.',
                'prefecture_id' => 1,
                'area_id' => null,
                'visit_date' => '2024-06-06',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '北海道札幌市中央区大通公園西4丁目',
                'event_longitude' => 141.3545,
                'event_latitude' => 43.0618,
                'language' => 'ja-JP',
                'created_at' => '2024-06-06',
                'updated_at' => NOW()
            ],
            [
                'id' => 22,
                'user_id' => 7,
                'title' => 'Nebuta Festival (Aomori)',
                'article' => 'large nighttime festival in Aomori',
                'prefecture_id' => 2,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '青森県青森市',
                'event_longitude' => 140.7405485,
                'event_latitude' => 40.824589,
                'language' => 'zh-Hans-CN',
                'created_at' => '2024-01-03',
                'updated_at' => NOW()
            ],
            [
                'id' => 23,
                'user_id' => 8,
                'title' => '花卷祭',
                'article' => '在岩手縣花卷市舉行的節日。花車和可攜式神轎是節日的亮點。',
                'prefecture_id' => 3,
                'area_id' => null,
                'visit_date' => '2024-07-07',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '岩手県花巻市上町3',
                'event_longitude' => 141.11653,
                'event_latitude' => 39.3855,
                'language' => 'zh-Hant-TW',
                'created_at' => '2024-07-07',
                'updated_at' => NOW()
            ],
            [
                'id' => 24,
                'user_id' => 9,
                'title' => '전국 코케시 인형 축제',
                'article' => '일본 전역에서 전통 코케시 인형이 모이는 행사입니다. 시연, 전시, 판매 및 코케시 페인팅 워크숍이 열립니다。',
                'prefecture_id' => 4,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '宮城県大崎市鳴子温泉湯元4',
                'event_longitude' => 140.71744,
                'event_latitude' => 38.744,
                'language' => 'ko-KR',
                'created_at' => '2024-03-03',
                'updated_at' => NOW()
            ],
            [
                'id' => 25,
                'user_id' => 13,
                'title' => 'Kanto Festival (Akita)',
                'article' => 'Compete in the skill of manipulating a Kanto (a long bamboo pole from which lanterns are hung)',
                'prefecture_id' => 5,
                'area_id' => null,
                'visit_date' => '2024-08-03',
                'start_date' => '2024-08-03',
                'end_date' => '2024-08-06',
                'event_address' => '秋田市中心部',
                'event_longitude' => 140.102521,
                'event_latitude' => 39.72,
                'language' => 'en-US',
                'created_at' => '2024-08-06',
                'updated_at' => NOW()
            ],
            [
                'id' => 26,
                'user_id' => 6,
                'title' => 'Yamagata Hanagasa Festival',
                'article' => 'Dancing parade with hanagasa',
                'prefecture_id' => 6,
                'area_id' => null,
                'visit_date' => '2024-08-05',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '山形県山形市十日町2-1-8',
                'event_longitude' => 140.3373,
                'event_latitude' => 38.2554,
                'language' => 'en-GB',
                'created_at' => '2024-08-05',
                'updated_at' => NOW()
            ],
            [
                'id' => 27,
                'user_id' => 6,
                'title' => 'Fukushima Waraji Festival',
                'article' => 'Carry big straw sandals and parade',
                'prefecture_id' => 7,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-08-01',
                'end_date' => '2024-08-02',
                'event_address' => '福島県福島市栄町',
                'event_longitude' => 140.4611,
                'event_latitude' => 37.7539,
                'language' => 'fr-FR',
                'created_at' => '2024-08-02',
                'updated_at' => NOW()
            ],
            [
                'id' => 28,
                'user_id' => 6,
                'title' => 'Mito Komon Festival (Japan\'s oldest festival, held annually on May 15)',
                'article' => 'Parades and fireworks displays associated with Mito Komon',
                'prefecture_id' => 8,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '水戸市中心部',
                'event_longitude' => 140.471,
                'event_latitude' => 36.3659,
                'language' => 'de-DE',
                'created_at' => '2024-03-07',
                'updated_at' => NOW()
            ],
            [
                'id' => 29,
                'user_id' => 7,
                'title' => 'Nikko Toshogu Shrine Spring Festival',
                'article' => 'Traditional festivals held at Toshogu Shrine',
                'prefecture_id' => 9,
                'area_id' => null,
                'visit_date' => '2024-05-17',
                'start_date' => '2024-05-17',
                'end_date' => '2024-05-18',
                'event_address' => '栃木県日光市山内2301',
                'event_longitude' => 139.5989,
                'event_latitude' => 36.7581,
                'language' => 'ja-JP',
                'created_at' => '2024-05-18',
                'updated_at' => NOW()
            ],
            [
                'id' => 30,
                'user_id' => 7,
                'title' => 'Kusatsu Onsen Yubatake Light-up',
                'article' => 'Events where Yubatake is illuminated',
                'prefecture_id' => 10,
                'area_id' => null,
                'visit_date' => '2024-01-01',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '吾妻郡草津町草津',
                'event_longitude' => 138.599,
                'event_latitude' => 36.618,
                'language' => 'zh-Hans-CN',
                'created_at' => '2024-01-01',
                'updated_at' => NOW()
            ],
            [
                'id' => 31,
                'user_id' => 8,
                'title' => 'Kawagoe Festival',
                'article' => 'Autumn festival with floats parading through the streets',
                'prefecture_id' => 11,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-10-21',
                'end_date' => '2024-10-22',
                'event_address' => '埼玉県川越市中心部',
                'event_longitude' => 139.48532,
                'event_latitude' => 35.9251,
                'language' => 'zh-Hant-TW',
                'created_at' => '2024-10-22',
                'updated_at' => NOW()
            ],
            [
                'id' => 32,
                'user_id' => 9,
                'title' => 'Narita Gion Festival (in Kyoto during the month of July, with high point on the 17th)',
                'article' => 'Traditional festival held at Naritasan Shinshoji Temple',
                'prefecture_id' => 12,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '千葉県成田市成田1',
                'event_longitude' => 140.3188,
                'event_latitude' => 35.7761,
                'language' => 'ko-KR',
                'created_at' => '2024-05-05',
                'updated_at' => NOW()
            ],
            [
                'id' => 33,
                'user_id' => 6,
                'title' => 'Sumida River Firework Festival (Tokyo)',
                'article' => 'Large-scale fireworks display held along the Sumida River',
                'prefecture_id' => 13,
                'area_id' => null,
                'visit_date' => '2024-07-28',
                'start_date' => '2024-07-28',
                'end_date' => '2024-07-28',
                'event_address' => '東京都台東区',
                'event_longitude' => 139.80302,
                'event_latitude' => 35.7128,
                'language' => 'en-US',
                'created_at' => '2024-07-28',
                'updated_at' => NOW()
            ],
            [
                'id' => 34,
                'user_id' => 6,
                'title' => 'Yokohama Port Opening Festival',
                'article' => 'Event celebrating the opening of the Port of Yokohama',
                'prefecture_id' => 14,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '神奈川県横浜市中区山下町2',
                'event_longitude' => 139.6500,
                'event_latitude' => 35.4000,
                'language' => 'en-US',
                'created_at' => '2024-06-06',
                'updated_at' => NOW()
            ],
            [
                'id' => 35,
                'user_id' => 6,
                'title' => 'Fireworks in Omagari',
                'article' => 'Known as the National Fireworks Competition, this fireworks display is held in Omagari City, Akita Prefecture.',
                'prefecture_id' => 5,
                'area_id' => null,
                'visit_date' => '2022-08-25',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '秋田県大仙市大曲通町1-131',
                'event_longitude' => 140.47245,
                'event_latitude' => 39.4536,
                'language' => 'en-US',
                'created_at' => '2022-08-25',
                'updated_at' => NOW()
            ],
            [
                'id' => 36,
                'user_id' => 6,
                'title' => 'Yokote Snow Festival',
                'article' => 'The highlight of this winter festival in Yokote City, Akita Prefecture, is the kamakura, or hanging scrolls.',
                'prefecture_id' => 5,
                'area_id' => null,
                'visit_date' => '2024-02-15',
                'start_date' => '2024-02-15',
                'end_date' => '2024-02-16',
                'event_address' => '秋田県横手市中央町82',
                'event_longitude' => 140.53601,
                'event_latitude' => 39.3465,
                'language' => 'en-US',
                'created_at' => '2023-02-16',
                'updated_at' => NOW()
            ],
            [
                'id' => 37,
                'user_id' => 6,
                'title' => 'hanagasa festival (Kamakura period)',
                'article' => 'A festival held in Yamagata City in which dancers with hanagasa hats parade through the city.',
                'prefecture_id' => 6,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '山形県山形市十日町1丁目3',
                'event_longitude' => 140.33552,
                'event_latitude' => 38.2476,
                'language' => 'en-US',
                'created_at' => '2024-07-07',
                'updated_at' => NOW()
            ],
            [
                'id' => 38,
                'user_id' => 7,
                'title' => 'Nagaoka Festival Fireworks Display',
                'article' => 'One of the three major fireworks festivals in Japan',
                'prefecture_id' => 15,
                'area_id' => null,
                'visit_date' => '2024-08-02',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '新潟県長岡市信濃川河川敷',
                'event_longitude' => 138.8520,
                'event_latitude' => 37.4463,
                'language' => 'en-US',
                'created_at' => '2024-08-02',
                'updated_at' => NOW()
            ],
            [
                'id' => 39,
                'user_id' => 7,
                'title' => 'Owara-Kaze-no-Bon Festival (Toyama)',
                'article' => 'Traditional dance and music festival',
                'prefecture_id' => 16,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-09-01',
                'end_date' => '2024-09-03',
                'event_address' => '富山県富山市八尾町東町2105番地1',
                'event_longitude' => 137.2137,
                'event_latitude' => 36.5781,
                'language' => 'en-US',
                'created_at' => '2024-09-03',
                'updated_at' => NOW()
            ],
            [
                'id' => 40,
                'user_id' => 7,
                'title' => 'Kanazawa Hyakumangoku Festival',
                'article' => 'Parade celebrating the entry of Toshiie Maeda into the castle',
                'prefecture_id' => 17,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '金沢市中心部',
                'event_longitude' => 136.656,
                'event_latitude' => 36.5613,
                'language' => 'en-US',
                'created_at' => '2024-08-08',
                'updated_at' => NOW()
            ],
            [
                'id' => 41,
                'user_id' => 8,
                'title' => 'Chichibu Night Festival (religious festival held in Chichibu, Saitama Prefecture)',
                'article' => 'The highlight of this winter festival is the fireworks and floats held at Chichibu Shrine.',
                'prefecture_id' => 11,
                'area_id' => null,
                'visit_date' => '2028-12-02',
                'start_date' => '2024-12-02',
                'end_date' => '2024-12-03',
                'event_address' => '埼玉県秩父市番場町1-34',
                'event_longitude' => 139.08533,
                'event_latitude' => 35.9917,
                'language' => 'en-US',
                'created_at' => '2028-12-03',
                'updated_at' => NOW()
            ],
            [
                'id' => 42,
                'user_id' => 8,
                'title' => 'Koenji Awa Odori Festival (Tokushima)',
                'article' => 'Awa Odori dance festival held in Koenji, Tokyo.',
                'prefecture_id' => 13,
                'area_id' => null,
                'visit_date' => '2029-08-21',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '東京都杉並区高円寺南4丁目5',
                'event_longitude' => 139.64924,
                'event_latitude' => 35.70560,
                'language' => 'en-US',
                'created_at' => '2029-08-21',
                'updated_at' => NOW()
            ],
            [
                'id' => 43,
                'user_id' => 8,
                'title' => 'Ueno Cherry Blossom Festival',
                'article' => 'This festival is held in Ueno Onshi Park, a well-known cherry blossom viewing spot.',
                'prefecture_id' => 13,
                'area_id' => null,
                'visit_date' => '2024-03-21',
                'start_date' => '2024-03-21',
                'end_date' => '2024-04-10',
                'event_address' => '東京都台東区上野公園',
                'event_longitude' => 139.77415,
                'event_latitude' => 35.71410,
                'language' => 'en-US',
                'created_at' => '2020-04-10',
                'updated_at' => NOW()
            ],
            [
                'id' => 44,
                'user_id' => 9,
                'title' => 'Fukui Phoenix Festival',
                'article' => 'Civic participation parade and fireworks display',
                'prefecture_id' => 18,
                'area_id' => null,
                'visit_date' => '2024-08-01',
                'start_date' => '2024-08-01',
                'end_date' => '2024-08-10',
                'event_address' => '福井県福井市中央公園周辺',
                'event_longitude' => 136.2191,
                'event_latitude' => 36.0641,
                'language' => 'en-US',
                'created_at' => '2024-08-10',
                'updated_at' => NOW()
            ],
            [
                'id' => 45,
                'user_id' => 9,
                'title' => 'Yoshida\'s Fire Festival (held at Yoshida Shrine in Kyoto on May 15)',
                'article' => 'Fire festival at the foot of Mt.',
                'prefecture_id' => 19,
                'area_id' => null,
                'visit_date' => '2024-08-26',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '富士吉田市',
                'event_longitude' => 138.8070,
                'event_latitude' => 35.4875,
                'language' => 'en-US',
                'created_at' => '2024-08-26',
                'updated_at' => NOW()
            ],
            [
                'id' => 46,
                'user_id' => 10,
                'title' => 'Festival of the Pillar (July 7th)',
                'article' => 'A large festival held once every seven years',
                'prefecture_id' => 20,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-04-01',
                'end_date' => '2024-04-21',
                'event_address' => '諏訪市',
                'event_longitude' => 138.113321,
                'event_latitude' => 36.0381,
                'language' => 'en-US',
                'created_at' => '2024-04-21',
                'updated_at' => NOW()
            ],
            [
                'id' => 47,
                'user_id' => 11,
                'title' => 'Kurihama Hananokuni Cosmos Festival',
                'article' => 'A cosmos festival held in Kurihama Hananokuni, where one million cosmos will be in full bloom.',
                'prefecture_id' => 14,
                'area_id' => null,
                'visit_date' => '2024-09-07',
                'start_date' => '2024-09-07',
                'end_date' => '2024-10-27',
                'event_address' => '神奈川県横須賀市神明町1番地1',
                'event_longitude' => 139.7048666,
                'event_latitude' => 35.2205633,
                'language' => 'en-US',
                'created_at' => '2024-10-27',
                'updated_at' => NOW()
            ],
            [
                'id' => 48,
                'user_id' => 11,
                'title' => 'Tokamachi Snow Festival',
                'article' => 'A winter festival held in Tokamachi City, Niigata Prefecture, featuring snow sculptures and fireworks.',
                'prefecture_id' => 15,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '新潟県十日町市',
                'event_longitude' => 37.1275826,
                'event_latitude' => 138.7553,
                'language' => 'en-US',
                'created_at' => '2024-09-09',
                'updated_at' => NOW()
            ],
            [
                'id' => 49,
                'user_id' => 6,
                'title' => 'Takayama Festival (held at Takayama City Hall on the last day of the 6th lunar month)',
                'article' => 'Gorgeous floats parade through the city',
                'prefecture_id' => 21,
                'area_id' => null,
                'visit_date' => '2024-04-14',
                'start_date' => '2024-04-14',
                'end_date' => '2024-04-14',
                'event_address' => '高山市',
                'event_longitude' => 137.252521,
                'event_latitude' => 36.1467,
                'language' => 'en-US',
                'created_at' => '2024-04-14',
                'updated_at' => NOW()
            ],
            [
                'id' => 50,
                'user_id' => 6,
                'title' => 'Hamamatsu Festival',
                'article' => 'Kite flying and Goten-yatai cart pulling',
                'prefecture_id' => 22,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '静岡県浜松市中田島砂丘',
                'event_longitude' => 137.7261,
                'event_latitude' => 34.7108,
                'language' => 'en-US',
                'created_at' => '2024-10-01',
                'updated_at' => NOW()
            ],
            [
                'id' => 51,
                'user_id' => 6,
                'title' => 'Tateyama Kurobe Snow Valley Festival',
                'article' => 'The highlight of this event is a wall of snow on the Tateyama Kurobe Alpine Route.',
                'prefecture_id' => 16,
                'area_id' => null,
                'visit_date' => '2024-08-08',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '富山県中新川郡立山町芦峅寺室堂3',
                'event_longitude' => 137.5962,
                'event_latitude' => 36.57739,
                'language' => 'en-US',
                'created_at' => '2024-08-08',
                'updated_at' => NOW()
            ],
            [
                'id' => 52,
                'user_id' => 7,
                'title' => 'Climbing Mt. Fuji',
                'article' => 'Fuji, the highest mountain in Japan.',
                'prefecture_id' => 22,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '静岡県富士宮市4',
                'event_longitude' => 138.6092357,
                'event_latitude' => 35.2248112,
                'language' => 'en-US',
                'created_at' => '2024-12-01',
                'updated_at' => NOW()
            ],
            [
                'id' => 53,
                'user_id' => 7,
                'title' => 'Nagoya Festival (July)',
                'article' => 'Procession of Nobunaga Oda, Hideyoshi Toyotomi, and Ieyasu Tokugawa',
                'prefecture_id' => 23,
                'area_id' => null,
                'visit_date' => '2024-09-09',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '愛知県名古屋市中区栄',
                'event_longitude' => 136.9085,
                'event_latitude' => 35.1709,
                'language' => 'en-US',
                'created_at' => '2024-09-09',
                'updated_at' => NOW()
            ],
            [
                'id' => 54,
                'user_id' => 8,
                'title' => 'Ise Jingu Shikinen Sengu (iaido shrine)',
                'article' => 'The relocation of the Jingu shrine, which takes place every 20 years',
                'prefecture_id' => 24,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '三重県伊勢市宇治館町1',
                'event_longitude' => 136.7250,
                'event_latitude' => 34.4875,
                'language' => 'en-US',
                'created_at' => '2024-11-01',
                'updated_at' => NOW()
            ],
            [
                'id' => 55,
                'user_id' => 9,
                'title' => 'Kyoto Gozan Okuribi Festival (May 5th)',
                'article' => 'The bonfire festival is held on five mountains in Kyoto City.',
                'prefecture_id' => 26,
                'area_id' => null,
                'visit_date' => '2024-10-10',
                'start_date' => null,
                'end_date' => null,
                'event_address' => '京都府京都市左京区如意ケ嶽1',
                'event_longitude' => 135.79845,
                'event_latitude' => 35.0301,
                'language' => 'en-US',
                'created_at' => '2024-10-10',
                'updated_at' => NOW()
            ],
            [
                'id' => 56,
                'user_id' => 10,
                'title' => 'Kishiwada Danjiri Festival',
                'article' => 'large floats',
                'prefecture_id' => 27,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => null,
                'end_date' => null,
                'event_address' => '大阪府岸和田市岸城町2',
                'event_longitude' => 135.37371,
                'event_latitude' => 35.0301,
                'language' => 'en-US',
                'created_at' => '2024-03-08',
                'updated_at' => NOW()
            ],
            [
                'id' => 57,
                'user_id' => 11,
                'title' => 'Nagahama Hikiyama Festival (held annually on May 15)',
                'article' => 'Gorgeous floats parade through the city',
                'prefecture_id' => 25,
                'area_id' => null,
                'visit_date' => '2024-04-09',
                'start_date' => '2024-04-09',
                'end_date' => '2024-04-17',
                'event_address' => '長浜市',
                'event_longitude' => 136.27871,
                'event_latitude' => 35.3808,
                'language' => 'en-US',
                'created_at' => '2024-04-17',
                'updated_at' => NOW()
            ],
            [
                'id' => 58,
                'user_id' => 11,
                'title' => 'Gion Festival (in Kyoto during the month of July, with high point on the 17th)',
                'article' => 'One of the three major festivals in Japan, the highlight is the spectacular Yamahoko-junko procession.',
                'prefecture_id' => 26,
                'area_id' => null,
                'visit_date' => '2024-07-01',
                'start_date' => '2024-07-01',
                'end_date' => '2024-07-31',
                'event_address' => '京都市中心部',
                'event_longitude' => 135.76812,
                'event_latitude' => 35.0116,
                'language' => 'en-US',
                'created_at' => '2024-07-31',
                'updated_at' => NOW()
            ],
            [
                'id' => 59,
                'user_id' => 11,
                'title' => 'Tenjin Festival',
                'article' => 'One of the three major festivals in Japan held at Osaka Temmangu Shrine',
                'prefecture_id' => 27,
                'area_id' => null,
                'visit_date' => '2024-07-24',
                'start_date' => '2024-07-24',
                'end_date' => '2024-07-25',
                'event_address' => '大阪府大阪市北区天神橋2丁目1-8',
                'event_longitude' => 135.5127,
                'event_latitude' => 34.6960,
                'language' => 'en-US',
                'created_at' => '2024-07-25',
                'updated_at' => NOW()
            ],
            [
                'id' => 60,
                'user_id' => 12,
                'title' => 'Sanbongsan Fog and Ice Festival',
                'article' => 'The highlight of this winter festival is the misty ice on Mt.',
                'prefecture_id' => 29,
                'area_id' => null,
                'visit_date' => '2020-01-21',
                'start_date' => '2024-01-21',
                'end_date' => '2024-02-10',
                'event_address' => '奈良県宇陀郡御杖村大字神末1790番地3',
                'event_longitude' => 136.0967,
                'event_latitude' => 34.5150,
                'language' => 'en-US',
                'created_at' => '2020-02-10',
                'updated_at' => NOW()
            ],
            [
                'id' => 61,
                'user_id' => 12,
                'title' => 'Hakozaki Shrine Hojo-e',
                'article' => 'A festival held at Hakozaki Shrine in Fukuoka City. You can enjoy stalls and traditional performing arts.',
                'prefecture_id' => 40,
                'area_id' => null,
                'visit_date' => '2021-09-12',
                'start_date' => '2024-09-12',
                'end_date' => '2024-09-18',
                'event_address' => '福岡県福岡市東区箱崎1丁目22-14',
                'event_longitude' => 130.41513,
                'event_latitude' => 33.6182,
                'language' => 'en-US',
                'created_at' => '2021-09-18',
                'updated_at' => NOW()
            ],
            [
                'id' => 62,
                'user_id' => 10,
                'title' => 'Kobe Luminarie',
                'article' => 'Illumination event to commemorate the victims of the Great Hanshin-Awaji Earthquake',
                'prefecture_id' => 28,
                'area_id' => null,
                'visit_date' => '2024-12-01',
                'start_date' => '2024-12-01',
                'end_date' => '2024-12-20',
                'event_address' => '神戸市中央区',
                'event_longitude' => 135.19781,
                'event_latitude' => 34.6951,
                'language' => 'en-US',
                'created_at' => '2024-12-20',
                'updated_at' => NOW()
            ],
            [
                'id' => 63,
                'user_id' => 11,
                'title' => 'Nara Tofukakukai',
                'article' => 'The whole area of Nara Park is decorated with candlelight',
                'prefecture_id' => 29,
                'area_id' => null,
                'visit_date' => '2024-08-01',
                'start_date' => '2024-08-01',
                'end_date' => '2024-08-10',
                'event_address' => '奈良市奈良公園',
                'event_longitude' => 135.8432,
                'event_latitude' => 34.685,
                'language' => 'en-US',
                'created_at' => '2024-08-10',
                'updated_at' => NOW()
            ],
            [
                'id' => 64,
                'user_id' => 12,
                'title' => 'Nachi Fire Festival (held at Nachi Shrine in Kyoto on May 15)',
                'article' => 'Fire Festival at Nachi Taisha Shrine',
                'prefecture_id' => 30,
                'area_id' => null,
                'visit_date' => '2024-07-14',
                'start_date' => '2024-07-14',
                'end_date' => '2024-07-14',
                'event_address' => '東牟婁郡那智勝浦町那智山',
                'event_longitude' => 135.8925833,
                'event_latitude' => 33.668972,
                'language' => 'en-US',
                'created_at' => '2024-07-14',
                'updated_at' => NOW()
            ],
            [
                'id' => 65,
                'user_id' => 11,
                'title' => 'Tottori Shanshan Festival (Tottori)',
                'article' => 'Summer festival featuring umbrella dance',
                'prefecture_id' => 31,
                'area_id' => null,
                'visit_date' => '2024-08-13',
                'start_date' => '2024-08-13',
                'end_date' => '2024-08-15',
                'event_address' => '鳥取市中心部',
                'event_longitude' => 134.2354,
                'event_latitude' => 35.5011,
                'language' => 'en-US',
                'created_at' => '2024-08-15',
                'updated_at' => NOW()
            ],
            [
                'id' => 66,
                'user_id' => 12,
                'title' => 'Autumn Momotaro Festival in Okayama',
                'article' => 'An event featuring local food and history. Visitors can enjoy gourmet food stalls, an outdoor stage for comedy, and historical talk shows.',
                'prefecture_id' => 33,
                'area_id' => null,
                'visit_date' => '2024-10-12',
                'start_date' => '2024-10-12',
                'end_date' => '2024-10-13',
                'event_address' => '岡山県岡山市北区丸の内',
                'event_longitude' => 133.9344645,
                'event_latitude' => 34.659958,
                'language' => 'en-US',
                'created_at' => '2024-10-13',
                'updated_at' => NOW()
            ],
            [
                'id' => 67,
                'user_id' => 13,
                'title' => 'Izumo Taisha Shrine\'s Shinzai Festival (held at Izumo Grand Shrine in Shimane Prefecture)',
                'article' => 'Mysterious festival where gods from all over Japan are said to gather at Izumo-taisha Shrine',
                'prefecture_id' => 32,
                'area_id' => null,
                'visit_date' => '2024-10-12',
                'start_date' => '2024-10-12',
                'end_date' => '2024-10-12',
                'event_address' => '出雲市大社町杵築東195',
                'event_longitude' => 132.686,
                'event_latitude' => 35.396,
                'language' => 'en-US',
                'created_at' => '2024-10-12',
                'updated_at' => NOW()
            ],
            [
                'id' => 68,
                'user_id' => 11,
                'title' => 'Hiroshima Flower Festival',
                'article' => 'A flower festival held mainly in Peace Memorial Park. Visitors can enjoy parades, stage events, flower displays, and more.',
                'prefecture_id' => 34,
                'area_id' => null,
                'visit_date' => '2024-05-03',
                'start_date' => '2024-05-03',
                'end_date' => '2024-05-05',
                'event_address' => '広島市中区大手町1-10',
                'event_longitude' => 132.455,
                'event_latitude' => 34.391,
                'language' => 'en-US',
                'created_at' => '2024-05-05',
                'updated_at' => NOW()
            ],
            [
                'id' => 69,
                'user_id' => 12,
                'title' => 'West Japan Yakitori Festival',
                'article' => 'A festival where local yakitori from all over western Japan gather. Visitors can enjoy eating comparisons and stage events.',
                'prefecture_id' => 35,
                'area_id' => null,
                'visit_date' => '2024-09-14',
                'start_date' => '2024-09-14',
                'end_date' => '2024-09-15',
                'event_address' => '山口県長門市東深川1000-157',
                'event_longitude' => 131.188,
                'event_latitude' => 34.371,
                'language' => 'en-US',
                'created_at' => '2024-09-15',
                'updated_at' => NOW()
            ],
            [
                'id' => 70,
                'user_id' => 12,
                'title' => 'Awa Odori Festival (Tokushima)',
                'article' => 'A traditional dance festival in Tokushima City where dancers dance to the call of "Yatsusaa."',
                'prefecture_id' => 36,
                'area_id' => null,
                'visit_date' => '2024-08-12',
                'start_date' => '2024-08-12',
                'end_date' => '2024-08-15',
                'event_address' => '徳島県徳島市',
                'event_longitude' => 134.554,
                'event_latitude' => 34.07,
                'language' => 'en-US',
                'created_at' => '2024-08-15',
                'updated_at' => NOW()
            ],
            [
                'id' => 71,
                'user_id' => 11,
                'title' => 'Marugame Castle Night Festa',
                'article' => 'A night festival set in Marugame Castle. Enjoy gourmet food and stage events.',
                'prefecture_id' => 37,
                'area_id' => null,
                'visit_date' => '2024-09-14',
                'start_date' => '2024-09-14',
                'end_date' => '2024-09-14',
                'event_address' => '香川県丸亀市一番丁',
                'event_longitude' => 133.799,
                'event_latitude' => 34.289,
                'language' => 'en-US',
                'created_at' => '2024-09-14',
                'updated_at' => NOW()
            ],
            [
                'id' => 72,
                'user_id' => 12,
                'title' => 'Ishizuchi Shrine Summer Festival',
                'article' => 'It is a heroic event in which a sacred image is carried on one\'s back to the summit of the mountain.',
                'prefecture_id' => 38,
                'area_id' => null,
                'visit_date' => '2024-07-01',
                'start_date' => '2024-07-01',
                'end_date' => '2024-07-10',
                'event_address' => '愛媛県西条市小松町石鎚',
                'event_longitude' => 133.179,
                'event_latitude' => 33.857,
                'language' => 'en-US',
                'created_at' => '2024-07-10',
                'updated_at' => NOW()
            ],
            [
                'id' => 73,
                'user_id' => 13,
                'title' => 'dance originating in Kochi Prefecture',
                'article' => 'Yosakoi dance festival held in Kochi City.',
                'prefecture_id' => 39,
                'area_id' => null,
                'visit_date' => '2024-08-09',
                'start_date' => '2024-08-09',
                'end_date' => '2024-08-12',
                'event_address' => '高知県高知市',
                'event_longitude' => 133.531,
                'event_latitude' => 33.559,
                'language' => 'en-US',
                'created_at' => '2024-08-12',
                'updated_at' => NOW()
            ],
            [
                'id' => 74,
                'user_id' => 11,
                'title' => 'Hakata Dontaku Port Festival',
                'article' => 'A festival held in Fukuoka City with parades and stage events.',
                'prefecture_id' => 40,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-05-03',
                'end_date' => '2024-05-04',
                'event_address' => '福岡県福岡市',
                'event_longitude' => 130.40172,
                'event_latitude' => 33.5903,
                'language' => 'en-US',
                'created_at' => '2024-05-04',
                'updated_at' => NOW()
            ],
            [
                'id' => 75,
                'user_id' => 12,
                'title' => 'Karatsu-kunchi',
                'article' => 'A festival held in Karatsu City, Saga Prefecture, featuring a gorgeous floats of floats.',
                'prefecture_id' => 41,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-11-02',
                'end_date' => '2024-11-04',
                'event_address' => '佐賀県唐津市',
                'event_longitude' => 129.96813,
                'event_latitude' => 33.4501,
                'language' => 'en-US',
                'created_at' => '2024-11-04',
                'updated_at' => NOW()
            ],
            [
                'id' => 76,
                'user_id' => 14,
                'title' => 'Nagasaki kunichi',
                'article' => 'The festival is held at Suwa Shrine in Nagasaki City and features dragon dances and boat floats.',
                'prefecture_id' => 42,
                'area_id' => null,
                'visit_date' => '2024-10-07',
                'start_date' => '2024-10-07',
                'end_date' => '2024-10-09',
                'event_address' => '長崎県長崎市',
                'event_longitude' => 129.87764,
                'event_latitude' => 32.7502,
                'language' => 'en-US',
                'created_at' => '2024-10-09',
                'updated_at' => NOW()
            ],
            [
                'id' => 77,
                'user_id' => 14,
                'title' => 'Hinokuni Festival (held in Kyoto during the month of July, with high point on the 17th)',
                'article' => 'A summer festival held in Kumamoto City. You can enjoy parades, fireworks displays, and stage events.',
                'prefecture_id' => 43,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-08-05',
                'end_date' => '2024-08-07',
                'event_address' => '熊本市中心部',
                'event_longitude' => 130.70785,
                'event_latitude' => 32.8031,
                'language' => 'en-US',
                'created_at' => '2024-08-07',
                'updated_at' => NOW()
            ],
            [
                'id' => 78,
                'user_id' => 15,
                'title' => 'Beppu Onsen Festival',
                'article' => 'A festival themed on Beppu Onsen (hot springs). There will be an onsen mikoshi (portable shrine), a fireworks display, and stage events.',
                'prefecture_id' => 44,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-04-05',
                'end_date' => '2024-04-15',
                'event_address' => '大分県別府市',
                'event_longitude' => 131.49166,
                'event_latitude' => 33.2846,
                'language' => 'en-US',
                'created_at' => '2024-04-15',
                'updated_at' => NOW()
            ],
            [
                'id' => 79,
                'user_id' => 13,
                'title' => 'Miyazaki Jingu Grand Festival',
                'article' => 'A large autumn festival held at Miyazaki Jingu Shrine. Visitors can enjoy portable shrines, parades, and stage events.',
                'prefecture_id' => 45,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-10-26',
                'end_date' => '2024-10-28',
                'event_address' => '宮崎県宮崎市宮崎神宮',
                'event_longitude' => 131.423581,
                'event_latitude' => 31.938152,
                'language' => 'en-US',
                'created_at' => '2024-10-28',
                'updated_at' => NOW()
            ],
            [
                'id' => 80,
                'user_id' => 14,
                'title' => 'Buddhist festival held on the day of Buddha\'s death (orig. 15th of the 2nd month, now 15th of the 3rd month)',
                'article' => 'An autumn festival held in Kagoshima City. Visitors can enjoy a parade, stage events, and a fireworks display.',
                'prefecture_id' => 46,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-11-02',
                'end_date' => '2024-11-03',
                'event_address' => '鹿児島市中心部',
                'event_longitude' => 130.55712,
                'event_latitude' => 31.5965,
                'language' => 'en-US',
                'created_at' => '2024-11-03',
                'updated_at' => NOW()
            ],
            [
                'id' => 81,
                'user_id' => 15,
                'title' => 'Okinawa All-Island Eisa Festival',
                'article' => 'Eisa dance festival held in Okinawa City.',
                'prefecture_id' => 47,
                'area_id' => null,
                'visit_date' => null,
                'start_date' => '2024-08-21',
                'end_date' => '2024-08-31',
                'event_address' => '沖縄県沖縄市',
                'event_longitude' => 127.80553,
                'event_latitude' => 26.3344,
                'language' => 'en-US',
                'created_at' => '2024-08-31',
                'updated_at' => NOW()
            ]
        ];

        $this->post->insert($posts);
    }
}
